export const CUSTOMER_LIST_REQUEST = 'CUSTOMER_LIST_REQUEST';
export const CUSTOMER_LIST_SUCCESS = 'CUSTOMER_LIST_SUCCESS';
export const CUSTOMER_LIST_FAIL = 'CUSTOMER_LIST_FAIL';
export const CUSTOMER_LIST_RESET = 'CUSTOMER_LIST_RESET';

export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const CUSTOMER_DETAILS_FAIL = 'CUSTOMER_DETAILS_FAIL';
export const CUSTOMER_DETAILS_RESET = 'CUSTOMER_DETAILS_RESET';

export const CUSTOMER_STATUS_UPDATE_REQUEST = 'CUSTOMER_STATUS_UPDATE_REQUEST';
export const CUSTOMER_STATUS_UPDATE_SUCCESS = 'CUSTOMER_STATUS_UPDATE_SUCCESS';
export const CUSTOMER_STATUS_UPDATE_FAIL = 'CUSTOMER_STATUS_UPDATE_FAIL';
export const CUSTOMER_STATUS_UPDATE_RESET = 'CUSTOMER_STATUS_UPDATE_RESET';
